export { Navbar } from "./Navbar";
export { Lead } from "./Lead";
export { Features } from "./Features";
export { Pricing } from "./Pricing";
export { FAQ } from "./FAQ";
export  { CTA } from "./CTA";
export { Footer } from "./Footer";
export { FirstHero } from "./FirstHero";
export { SecondHero } from "./SecondHero";
