import Navbar from "@/design/components/Navbar";
import '@/styles/globals.css';
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';

import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Montserrat, Montserrat_Alternates } from 'next/font/google';
import Link from 'next/link';
import { IoLogoFacebook, IoLogoInstagram, IoLogoTwitter } from 'react-icons/io5';

import { Logo } from '@/design/components/logo';
import { Toaster } from '@/design/components/ui/toaster';
import { cn } from '@/utils/cn';

import { Navigation } from './navigation';
import { Footer } from '@/design/templates/Footer';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

const montserratAlternates = Montserrat_Alternates({
  variable: '--font-montserrat-alternates',
  weight: ['500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={cn('font-sans antialiased', montserrat.variable, montserratAlternates.variable)}>
        <NextIntlClientProvider messages={messages}>
          <div className='m-auto flex h-full max-w-[1440px] flex-col px-4'>
            <AppBar
              lang={locale}
            />
              <main className='relative flex-1'>
                <div className='relative h-full'>
                  {children}
                </div>
              </main>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

async function AppBar({ lang }: { lang: string }) {
  return (
    <header className='flex items-center justify-between py-8'>
      <Logo />
      <Navigation
        lang={lang}
      />
    </header>
  );
}
