import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Suspense } from "react";
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { Navbar, Footer } from '@/design/templates'
import { getLandingNavbarConfig } from "@/config/ui/landing";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function LandingLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div className='m-auto flex h-full w-full flex-col'>
      <Suspense fallback="...">
        <Navbar
          items={getLandingNavbarConfig().mainNav}
        />
      </Suspense>
        <main className='relative flex-1'>
          <div className='relative h-full'>
            {children}
          </div>
        </main>
      <Footer />
    </div>
  );
}
