import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Suspense } from 'react'
import { Navbar, Footer } from '@/design/templates'
import { getLandingNavbarConfig } from '@/config/ui/landing'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default async function ProductLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      <Suspense fallback="...">
        <Navbar
          items={(await getLandingNavbarConfig()).mainNav}
        />
      </Suspense>
      <main className='relative flex-1'>
        <div className='relative h-full'>
          {children}
        </div>
      </main>
      <Footer />
    </>
  );
}
